version: '3'

services:
    app:
        build:
            context: .
            dockerfile: docker/dockerfiles/nginx.dockerfile
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:5.7.29
        container_name: mysql
        restart: unless-stopped
        tty: true
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: test-lendings
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: example/landings:latest
        container_name: php
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel

    npm:
        image: node:14
        working_dir: /var/www/html
        container_name: npm
        entrypoint: [ "npm" ]
        volumes:
            - .:/var/www/html
        ports:
            - "5173:5173"
        networks:
            - laravel
d
networks:
    laravel:

volumes:
    mysql:
        driver: local
